blog/urls.py
from django.conf.urls import url

from . import views

app_name = "blog"
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^(?P<category>[^/]+)/(?P<title>[^/]+)$', views.detail, name = 'detail'),
    url(r'^(?P<category>[^/]+)$', views.category, name = 'category'),
    url(r'^about_me$', views.about_me, name = 'about_me')
]

blogProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class PostType(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Post(models.Model):
    #标题
    title = models.CharField(max_length = 100)
    def __str__(self):
        return self.title
    #正文
    body = models.TextField()
    #创建时间和修改时间
    created_time = models.DateTimeField()
    modify_time = models.DateTimeField()
    #文章类型
    post_type = models.ForeignKey(PostType)
    type_src = models.CharField(max_length = 100, blank = True)
    #文章摘要
    excerpt = models.CharField(max_length = 200, blank = True)
    #分类和标签
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank = True)
    #作者
    author = models.ForeignKey(User)
    
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs = {'category' : self.category.name,
                                                'title' : self.title
                                                })
        

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from django.shortcuts import render, get_object_or_404
import markdown

# Create your views here.
def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={
                                'title': 'Bymost',
                                'description': 'Beyond The Most',
                                'post_list' : post_list
                                })

def detail(request, category, title):
    post = get_object_or_404(Post, title = title)
    return render(request, 'blog/single.html', context = {'post' : post})

def category(request, category):
    return render(request, 'blog/about_me.html')

def about_me(request):
    return render(request, 'blog/about_me.html')

templates/blog/about_me.html
{%load staticfiles %}
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>About_me | Bymost</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body class="single">

		<!-- Wrapper -->
			<div id="wrapper">

				{% include 'blog/header.html' %}

				<!-- Main -->
					<div id="main">

						<!-- Post -->
							<article class="post">
                                <section>
								    <span class="image right"><img src="{% static 'blog/images/avatar.jpg' %}" alt="" /></span>
								    <p>
                                        只修电脑，绝不过夜！ 
                                    <ul>
                                        <li>iOS/Swift Developer</li>
                                        <li>Python Developer</li>
                                        <li>机器学习，数据分析及数据挖掘爱好者</li>
                                        <li>高度近视抓瞎选手</li>
                                        <li>bymost名字灵感来源于<a href="www.byvoid.com">byvoid</a>,即小名多多的beyond the most中二翻译简称</li>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        </br>
                                        {% include 'blog/footer.html' %}
                                    </ul>
                                    </p>
                                </section>
							</article>
					</div>

				

			</div>

		<!-- Scripts -->
			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

	</body>
</html>

templates/blog/footer.html
<!-- Footer -->
<section id="footer">
    {% include 'blog/icon.html'%}
    <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>.</p>
</section>

templates/blog/header.html
{% load staticfiles %}
<!-- Header -->
<header id="header">
    <h1><a href="{%url 'blog:index' %}"> Beyond the most </a></h1>
    <nav class="links">
        <ul>
            <li><a href="{%url 'blog:index' %}">Home</a></li>
            <li><a href="{%url 'blog:about_me' %}">About</a></li>
        </ul>
    </nav>
    <nav class="main">
        <ul>
            <li class="search">
                <a class="fa-search" href="#search">Search</a>
                <form id="search" method="get" action="#">
                    <input type="text" name="query" placeholder="Search" />
                </form>
            </li>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
            </li>
        </ul>
    </nav>
</header>

<!-- Menu -->
<section id="menu">

    <!-- Search -->
        <section>
            <form class="search" method="get" action="#">
                <input type="text" name="query" placeholder="Search" />
            </form>
        </section>

    <!-- Links -->
        <section>
            <ul class="links">
                <li>
                    <a href="{%url 'blog:index' %}">
                        <h3>Home</h3>
                        <p>Welcome</p>
                    </a>
                </li>
                <li>
                    <a href="{%url 'blog:about_me' %}">
                        <h3>About</h3>
                        <p>About me</p>
                    </a>
                </li>
            </ul>
        </section>

    <!-- Actions -->
        <section>
            <ul class="actions vertical">
                <li><a href="/admin" class="button big fit">Log In</a></li>
            </ul>
        </section>

</section>

templates/blog/icon.html
<ul class="icons">
        <li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
        <li><a href="Mailto:zhtibrim@gmail.com" class="fa-envelope"><span class="label">Email</span></a></li>
        <li><a href="#" class="fa-github"><span class="label">Github</span></a></li>
</ul>

templates/blog/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{{title}} | {{description}}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="{% static 'blog/assets/js/ie/html5shiv.js' %}"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'blog/assets/css/ie9.css' %}" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="{% static 'blog/assets/css/ie8.css' %}" /><![endif]-->
	</head>
	<body>

		<!-- Wrapper -->
			<div id="wrapper">

				{% include "blog/header.html"%}

				<!-- Main -->
					<div id="main">
						{% for post in post_list %}
							<!-- Post -->
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="{%url 'blog:detail' title=post.title category=post.category.name %}">{{post.title}}</a></h2>
										 <!-- <p> -->
											 {{post.excerpt}}
											<!-- </p>  -->
									</div>
									<div class="meta">
										<time class="published" datetime="{{ post.created_time }}">{{ post.created_time}}</time>
										<a href="{%url 'blog:about_me' %}" class="author"><span class="name">{{ post.author }}</span><img src="{% static 'blog/images/avatar.jpg' %}" alt="{{ post.author }}" /></a>
									</div>
								</header>
								<!-- <a href="#" class="image featured"><img src="{% static 'blog/images/pic01.jpg' %}" alt="" /></a> -->
								  <!-- <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>   -->
									<p>
										{{ post.body | safe}} 
									</p>
								<footer>
									<ul class="actions">
										<li><a href="{{ post.get_absolute_url }}" class="button">Continue Reading</a></li>
									</ul>
									<ul class="stats">
										<li><a href="">{{ post.category }}</a></li>
										<li><a href="" class="icon fa-comment">0</a></li>
									</ul>
								</footer>
							</article>
						{% endfor %}

						<!-- Pagination -->
							<ul class="actions pagination">
								<li><a href="" class="disabled button previous">Previous Page</a></li>
								<li><a href="" class="disabled button next">Next Page</a></li>
							</ul>

					</div>

				<!-- Sidebar -->
					<section id="sidebar">

						<!-- Intro -->
							<section id="intro">
								<a href="{%url 'blog:index' %}" class="logo"><img src="{% static 'blog/images/logo.jpg' %}" alt="" /></a>
								<header>
									<h2>Bymost</h2>
									<p>Beyond The Most</p>
									{% include 'blog/icon.html'%}
								</header>
							</section>

						<!-- About -->
							<section class="blurb">
								<h2>About Me</h2>
								<p>iOS Developer, Python, Machine_learning</p>
								<ul class="actions">
									<li><a href="{%url 'blog:about_me'%}" class="button">Learn More</a></li>
								</ul>
							</section>
					</section>

			</div>
			<div align = "center">
				<section id="footer">
					<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>.by<a href="{%url 'blog:index'%}">多多</a></p>
				</section>
			</div>
		<!-- Scripts -->
			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

	</body>
</html>

templates/blog/single.html
{%load staticfiles %}
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{{post.title }} | Bymost</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="{% static 'blog/assets/css/main.css' %}" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body class="single">

		<!-- Wrapper -->
			<div id="wrapper">

				{% include 'blog/header.html' %}

				<!-- Main -->
					<div id="main">

						<!-- Post -->
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
										<p>{{post.excerpt}}</p>
									</div>
									<div class="meta">
										<time class="published" datetime="{{ post.created_time }}">{{ post.created_time }}</time>
										<a href="#" class="author"><span class="name">{{ post.author }}</span><img src="{% static 'blog/images/avatar.jpg' %}" alt="" /></a>
									</div>
								</header>
								<span class="image featured"><img src="{% static 'blog/images/pic01.jpg' %}" alt="" /></span>
								<p>
									{{ post.body | safe }}
								</p>
								<footer>
									<ul class="stats">
										<li><a href="#">{{post.category}}</a></li>
										<li><a href="#" class="icon fa-comment">0</a></li>
									</ul>
								</footer>
							</article>

					</div>

				{% include 'blog/footer.html' %}

			</div>

		<!-- Scripts -->
			<script src="{% static 'blog/assets/js/jquery.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/skel.min.js' %}"></script>
			<script src="{% static 'blog/assets/js/util.js' %}"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="{% static 'blog/assets/js/main.js' %}"></script>

	</body>
</html>